configs:
  cm:
    timeout.reconciliation: 30s
    accounts.devops: apiKey,login

  rbac:
    policy.default: role:readonly
    policy.csv: |
      # групі devops даємо роль admin
      g, devops, role:admin

server:
  service:
    type: ClusterIP

  extraArgs:
    - --insecure

redis:
  enabled: true

### added for application
applicationSet:
  enabled: true

